# SPDX-License-Identifier: Apache-2.0
"""Save/validate/export domain owner behind the HwpxDocument facade (S-084)."""

from __future__ import annotations

import warnings
from os import PathLike
from typing import TYPE_CHECKING, Any, BinaryIO, Sequence

from ..opc.package import _UNCHECKED_SAVE_TOKEN
from ..quality import QualityPolicy
from ..quality.report import OpenSafetyReport

if TYPE_CHECKING:
    from hwpx.document import HwpxDocument
    from ..quality import VisualCompleteReport
    from ..tools.validator import ValidationReport


def _summarize_validation_issues(issues: Sequence[Any], *, limit: int = 5) -> str:
    selected = [str(issue) for issue in issues[:limit]]
    remaining = len(issues) - len(selected)
    summary = "; ".join(selected)
    if remaining > 0:
        summary += f" ... and {remaining} more"
    return summary


def export_text(doc: "HwpxDocument", **kwargs: object) -> str:
    """Export content as plain text.  Keyword args forwarded to :func:`~hwpx.tools.exporter.export_text`."""
    from ..tools.exporter import export_text
    return export_text(doc, **kwargs)  # type: ignore[arg-type]


def export_html(doc: "HwpxDocument", **kwargs: object) -> str:
    """Export content as HTML.  Keyword args forwarded to :func:`~hwpx.tools.exporter.export_html`."""
    from ..tools.exporter import export_html
    return export_html(doc, **kwargs)  # type: ignore[arg-type]


def export_markdown(doc: "HwpxDocument", **kwargs: object) -> str:
    """Export content as Markdown.  Keyword args forwarded to :func:`~hwpx.tools.exporter.export_markdown`."""
    from ..tools.exporter import export_markdown
    return export_markdown(doc, **kwargs)  # type: ignore[arg-type]


def export_rich_markdown(doc: "HwpxDocument", **kwargs: object) -> str:
    """Export rich Markdown preserving inline styles, tables, footnotes, hyperlinks, images, and shape text.

    Keyword args forwarded to :func:`~hwpx.tools.markdown_export.export_markdown`.
    """
    from ..tools.markdown_export import export_markdown as _rich
    return _rich(doc, **kwargs)  # type: ignore[arg-type]


def validate(doc: "HwpxDocument") -> "ValidationReport":
    """Run XML schema validation on the current document state.

    Returns a :class:`~hwpx.tools.validator.ValidationReport` with
    any issues found.  This does **not** require ``validate_on_save``
    to be enabled.
    """
    from ..tools.validator import validate_document

    return validate_document(
        _to_bytes_for_validation(doc)
    )


def _run_pre_save_validation(doc: "HwpxDocument") -> None:
    """Raise if validate_on_save is enabled and the document is invalid."""
    if not doc.validate_on_save:
        return
    report = doc.validate()
    if not report.ok:
        msgs = _summarize_validation_issues(report.issues)
        raise ValueError(f"Document validation failed: {msgs}")


def _run_open_safety_validation(doc: "HwpxDocument", archive_bytes: bytes) -> None:
    """Raise if generated bytes are unsafe to hand to an HWPX editor."""

    from ..tools.package_validator import validate_editor_open_safety

    report = validate_editor_open_safety(archive_bytes)
    if not report.ok:
        raise ValueError(
            "Generated HWPX package failed open-safety validation: "
            + report.summary
        )


def _gate_and_write(
    doc: "HwpxDocument",
    archive_bytes: bytes,
    *,
    output_path: str | PathLike[str] | None = None,
    output_stream: BinaryIO | None = None,
    source_label: str,
) -> VisualCompleteReport:
    """Funnel a serialized archive through the SavePipeline (transparent).

    ``_to_bytes_raw`` already ran open-safety and raised on failure, so the
    gate is transparent here — it performs the single atomic write and returns
    the uniform report. Raises if the gate unexpectedly rejects the bytes.
    """

    report = doc._save_pipeline.run(
        archive_bytes,
        output_path=output_path,
        output_stream=output_stream,
        quality=QualityPolicy.transparent(),
        open_safety=OpenSafetyReport.passed("validated during serialize"),
        publish="on_pass",
        source_label=source_label,
    )
    if not report.ok:
        detail = "; ".join(str(error) for error in report.errors)
        raise ValueError(f"Document save failed the quality gate: {detail}")
    return report


def save_to_path(doc: "HwpxDocument", path: str | PathLike[str]) -> str | PathLike[str]:
    """Persist pending changes to *path* and return the same path."""

    _run_pre_save_validation(doc)
    archive_bytes = doc._to_bytes_raw(reset_dirty=False)
    _gate_and_write(doc,
        archive_bytes, output_path=path, source_label="document.save_to_path"
    )
    _mark_save_clean(doc)
    return path


def save_to_stream(doc: "HwpxDocument", stream: BinaryIO) -> BinaryIO:
    """Persist pending changes to *stream* and return the same stream."""

    _run_pre_save_validation(doc)
    archive_bytes = doc._to_bytes_raw(reset_dirty=False)
    _gate_and_write(doc,
        archive_bytes, output_stream=stream, source_label="document.save_to_stream"
    )
    _mark_save_clean(doc)
    return stream


def save_report(
    doc: "HwpxDocument",
    path_or_stream: str | PathLike[str] | BinaryIO | None = None,
    *,
    quality: QualityPolicy | None = None,
    before: str | PathLike[str] | None = None,
    edit_mask: Any | None = None,
    ledger: Any | None = None,
) -> VisualCompleteReport:
    """Save through the SavePipeline and return the full ``VisualCompleteReport``.

    This is the canonical Phase-B write: it funnels through the one gate and
    returns the uniform report (open-safety, reference integrity, and — when
    the policy renders and a Hancom oracle is reachable — the visual verdict).
    ``quality`` defaults to :meth:`QualityPolicy.transparent` so the call is a
    drop-in for ``save_to_path`` that simply also hands back the report; pass
    ``QualityPolicy.strict()`` (or ``render_check="required"``) to demand the
    oracle-verified ``visual_complete`` tier (plan §0.0).

    Like the legacy savers it raises only if the serialize step's open-safety
    check fails; all other gate outcomes are returned in the report.
    """

    _run_pre_save_validation(doc)
    archive_bytes = doc._to_bytes_raw(reset_dirty=False)

    output_path: str | PathLike[str] | None = None
    output_stream: BinaryIO | None = None
    if isinstance(path_or_stream, (str, PathLike)):
        output_path = path_or_stream
    elif path_or_stream is not None:
        output_stream = path_or_stream

    report = doc._save_pipeline.run(
        archive_bytes,
        output_path=output_path,
        output_stream=output_stream,
        quality=quality or QualityPolicy.transparent(),
        before=before,
        edit_mask=edit_mask,
        ledger=ledger,
        reference_document=doc,
        source_label="document.save_report",
    )
    if report.ok:
        _mark_save_clean(doc)
    return report


def to_bytes(doc: "HwpxDocument") -> bytes:
    """Serialize pending changes and return the HWPX archive as bytes."""

    _run_pre_save_validation(doc)
    return doc._to_bytes_raw()


def _to_bytes_raw(
    doc: "HwpxDocument",
    *,
    reset_dirty: bool = True,
) -> bytes:
    """Serialize and run editor-open safety validation.

    When ``reset_dirty`` is ``False``, the document remains marked as
    modified after the archive snapshot is generated.
    """
    updates = doc._root.serialize()
    if updates:
        for part_name, payload in updates.items():
            doc._package.set_part(part_name, payload)
    result = doc._package._save_to_bytes(
        verify_open_safety=True,
        mark_clean=False,
    )
    if isinstance(result, bytes):
        doc._run_open_safety_validation(result)
        if reset_dirty:
            _mark_save_clean(doc)
        return result
    raise TypeError("package.save(None) must return bytes")


def _to_bytes_for_validation(doc: "HwpxDocument") -> bytes:
    """Serialize current state for document validation without handing bytes to callers."""

    updates = doc._root.serialize()
    return doc._package._save_bytes_unchecked(
        updates,
        _unchecked_token=_UNCHECKED_SAVE_TOKEN,
    )


def _mark_save_clean(doc: "HwpxDocument") -> None:
    doc._root.reset_dirty()
    doc._package.version_info.mark_clean()


def save(
    doc: "HwpxDocument",
    path_or_stream: str | PathLike[str] | BinaryIO | None = None,
) -> str | PathLike[str] | BinaryIO | bytes:
    """Deprecated compatibility wrapper around save_to_path/save_to_stream/to_bytes.

    Deprecated:
        ``save()``는 하위 호환을 위해 유지되며 향후 제거될 수 있습니다.
        - 경로 저장: ``save_to_path(path)``
        - 스트림 저장: ``save_to_stream(stream)``
        - 바이트 반환: ``to_bytes()``
    """

    warnings.warn(
        "HwpxDocument.save()는 deprecated 예정입니다. "
        "save_to_path()/save_to_stream()/to_bytes() 사용을 권장합니다.",
        DeprecationWarning,
        stacklevel=2,
    )
    if path_or_stream is None:
        return doc.to_bytes()
    if isinstance(path_or_stream, (str, PathLike)):
        return doc.save_to_path(path_or_stream)
    return doc.save_to_stream(path_or_stream)
