# SPDX-License-Identifier: Apache-2.0
"""openrate corpus v3 — the CURRENT stack's authoring surfaces, reduced scope.

Why v3 exists
=============

The published open-rate figures were measured on a corpus *generated by* the
3.4.1-era stack (v1 frozen 2026-07, v2 additive). Fourteen tags and two majors
shipped since, and none of the authoring surfaces added in 4.x/5.x — form
fields, equations, charts, footnotes, edit plans, check boxes — exist in that
corpus. Re-running Hancom over the same frozen bytes would measure nothing
about the current serializer, so v3 regenerates with the CURRENT stack.

Reduced scope, stated rather than hidden
========================================

v3 is deliberately NOT a 497-file re-measurement. It is a ~120-file additive
tree: one small baseline stratum for comparability plus one stratum per new
authoring surface. The published metrics page must present v3 next to the
dated v1/v2 figures, never as a replacement for them. Growing the measurement
honestly beats inflating it to protect a headline.

Strata (all deterministic — fixed seeds, bank rotation, no wall clock):

* ``baseline-regen``      30  plain paragraphs / tables / dedicated shapes,
                              the v1 authored shapes re-emitted by current core
* ``authored-footnote``   15  footnotes + endnotes (5.5 render-contract repair)
* ``authored-formfield``  15  CLICKHERE create + style-preserving fill (5.1)
* ``authored-equation``   15  latex_to_eqedit over verified tokens (5.2);
                              an UnsupportedLatexError is recorded as withheld,
                              never skipped silently
* ``authored-chart``      15  office.charting XML -> core add_chart (5.3)
* ``authored-checkbox``   15  add_check_box / set_check_box round trip (5.7)
* ``edit-plan``           15  hwpx.plan.apply_edit_plan multi-op outputs (5.6)

Like v1, this runs from the automation environment: the chart stratum composes
its ChartML through ``hwpx_automation.office.charting`` (core deliberately does
not own chart composition). Everything else is pure core.

    cd python-hwpx-automation
    .venv/bin/python ../python-hwpx/scripts/generate_openrate_corpus_v3.py

Generation ONLY — no Hancom oracle here. Every produced file gets the static
``validate_editor_open_safety`` pre-filter (necessary, not sufficient); the
real verdict comes from the Windows box run. The manifest records the exact
generating stack so the measurement can never again be published without
saying what produced it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Callable

PYTHON_HWPX = Path(__file__).resolve().parent.parent
HWPX_ROOT = PYTHON_HWPX.parent
sys.path.insert(0, str(PYTHON_HWPX / "scripts"))

from generate_openrate_corpus import (  # noqa: E402
    DATE_BANK,
    DEPT_BANK,
    ORG_BANK,
    OUT_DIR,
    OUT_DIR_V2,
    SUBJECT_BANK,
    cycle,
    record,
    sha256_file,
)

from hwpx import HwpxDocument  # noqa: E402

OUT_DIR_V3 = PYTHON_HWPX / "work" / "openrate-corpus-v3"
MANIFEST_SCHEMA = "hwpx.openrate.frozen-manifest.v3"
BOX_ROOT = "C:\\openrate\\v3"

#: Frozen negative controls already judged on the box in the v2 run. They are
#: referenced by box path so the oracle harness is re-validated (a control that
#: opens clean marks the whole run harness-invalid), without regenerating or
#: re-shipping corrupt bytes.
BOX_NEGATIVE_CONTROLS = (
    "C:\\openrate\\m9-full\\v1\\corrupt_section.hwpx",
    "C:\\openrate\\m9-full\\v1\\corrupt_header.hwpx",
    "C:\\openrate\\m9-full\\v1\\missing_section.hwpx",
)

#: Render-verified LaTeX samples for the equation stratum. Anything the
#: converter refuses is recorded as withheld with the typed reason — the
#: emit-rate discipline, not a silent skip.
EQUATION_LATEX_BANK = (
    r"\frac{1}{3} + \frac{2}{3} = 1",
    r"x^2 + y^2 = z^2",
    r"\sqrt{2} \times \sqrt{8} = 4",
    r"\int_{0}^{1} x^2 dx = \frac{1}{3}",
    r"\sum_{i=1}^{n} i = \frac{n(n+1)}{2}",
    r"\alpha + \beta = \gamma",
    r"a_{1} + a_{2} + a_{3}",
    r"\frac{a+b}{c-d}",
)


def _base_document(idx: int, title: str) -> HwpxDocument:
    document = HwpxDocument.new()
    document.add_paragraph(f"{cycle(ORG_BANK, idx)} {title}")
    document.add_paragraph(f"제목: {cycle(SUBJECT_BANK, idx)}")
    document.add_paragraph(f"시행일: {cycle(DATE_BANK, idx)} · 담당: {cycle(DEPT_BANK, idx)}")
    return document


def gen_baseline_regen(bucket_dir: Path) -> list[dict[str, Any]]:
    """v1's authored shapes, re-emitted by the current core serializer."""

    records: list[dict[str, Any]] = []
    for idx in range(30):
        rec_id = f"v3-baseline-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        try:
            document = _base_document(idx, "일반 안내")
            if idx % 3 == 1:
                table = document.add_table(3, 3, width=42000)
                for column, value in enumerate(("구분", "내용", "비고")):
                    table.cell(0, column).text = value
                for row in (1, 2):
                    for column in range(3):
                        table.cell(row, column).text = f"항목 {row}-{column}"
            if idx % 3 == 2:
                variant = (idx // 3) % 3
                if variant == 0:
                    document.add_rectangle(14400, 7200, fill_color="#CCE5FF")
                elif variant == 1:
                    document.add_line(0, 0, 14400, 0)
                else:
                    document.add_ellipse(10000, 6000, fill_color="#FFD9CC")
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="baseline-regen", seed=str(idx),
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001 - withheld is the honest record
            records.append(record(
                rec_id=rec_id, bucket="baseline-regen", seed=str(idx),
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_footnote(bucket_dir: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for idx in range(15):
        rec_id = f"v3-footnote-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        try:
            document = _base_document(idx, "각주 표본")
            paragraph = document.add_paragraph(f"본문 문단 {idx} — 각주가 달린 문장입니다.")
            for note_index in range(1 + idx % 3):
                document.add_footnote(
                    f"각주 {note_index + 1}: {cycle(SUBJECT_BANK, idx + note_index)}",
                    paragraph=paragraph,
                )
            if idx % 3 == 0:
                document.add_endnote(f"미주: {cycle(DEPT_BANK, idx)} 참고", paragraph=paragraph)
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="authored-footnote", seed=str(idx),
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="authored-footnote", seed=str(idx),
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_formfield(bucket_dir: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for idx in range(15):
        rec_id = f"v3-formfield-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        try:
            document = _base_document(idx, "누름틀 표본")
            field_count = 1 + idx % 3
            for field_index in range(field_count):
                document.add_form_field(
                    f"field_{idx}_{field_index}",
                    prompt=f"{cycle(DEPT_BANK, idx + field_index)} 입력",
                )
            # fill half the documents so both authored and filled shapes are judged
            if idx % 2 == 0:
                document.fill_form_field(
                    cycle(ORG_BANK, idx), name=f"field_{idx}_0",
                )
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="authored-formfield", seed=str(idx),
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="authored-formfield", seed=str(idx),
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_equation(bucket_dir: Path) -> list[dict[str, Any]]:
    from hwpx.equation import latex_to_eqedit

    records: list[dict[str, Any]] = []
    for idx in range(15):
        rec_id = f"v3-equation-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        latex = EQUATION_LATEX_BANK[idx % len(EQUATION_LATEX_BANK)]
        try:
            script = latex_to_eqedit(latex)
            document = _base_document(idx, "수식 표본")
            document.add_paragraph(f"수식 {idx}:")
            document.add_equation(script)
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="authored-equation", seed=latex,
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="authored-equation", seed=latex,
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_chart(bucket_dir: Path) -> list[dict[str, Any]]:
    from hwpx_automation.office.charting import ChartSeries, build_chart_ml

    records: list[dict[str, Any]] = []
    chart_types = ("bar", "line", "pie")
    for idx in range(15):
        rec_id = f"v3-chart-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        chart_type = chart_types[idx % len(chart_types)]
        try:
            categories = [cycle(DEPT_BANK, idx + offset) for offset in range(3)]
            series = [
                ChartSeries(
                    name=f"{cycle(ORG_BANK, idx)} 지표",
                    values=[float(10 + idx), float(20 + idx % 7), float(15 + idx % 5)],
                )
            ]
            if chart_type != "pie":
                series.append(ChartSeries(
                    name="전년 동기",
                    values=[float(8 + idx % 4), float(18 + idx % 3), float(12 + idx % 6)],
                ))
            chart_xml = build_chart_ml(
                chart_type, categories, series, title=f"{chart_type} 표본 {idx}",
            )
            document = _base_document(idx, "차트 표본")
            document.add_chart(chart_xml, size=(60000, 40000))
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="authored-chart", seed=f"{chart_type}:{idx}",
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="authored-chart", seed=f"{chart_type}:{idx}",
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_checkbox(bucket_dir: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for idx in range(15):
        rec_id = f"v3-checkbox-{idx:03d}"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        try:
            document = _base_document(idx, "체크박스 표본")
            box_count = 1 + idx % 3
            for box_index in range(box_count):
                document.add_check_box(
                    f"{cycle(SUBJECT_BANK, idx + box_index)} 여부",
                    checked=(idx + box_index) % 2 == 0,
                    name=f"chk_{idx}_{box_index}",
                )
            if idx % 3 == 0:
                # exercise the SET path on an authored box, not only CREATE
                document.set_check_box(True, name=f"chk_{idx}_0")
            document.save_to_path(str(out_path))
            records.append(record(
                rec_id=rec_id, bucket="authored-checkbox", seed=str(idx),
                output_path=out_path, produced=True,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="authored-checkbox", seed=str(idx),
                output_path=None, produced=False,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


def gen_edit_plan(bucket_dir: Path) -> list[dict[str, Any]]:
    """The atomic plan executor's OUTPUT documents are the corpus items."""

    from hwpx.plan import apply_edit_plan

    records: list[dict[str, Any]] = []
    base_dir = bucket_dir / "_bases"
    base_dir.mkdir(parents=True, exist_ok=True)
    for idx in range(15):
        rec_id = f"v3-editplan-{idx:03d}"
        base_path = base_dir / f"{rec_id}-base.hwpx"
        out_path = bucket_dir / f"{rec_id}.hwpx"
        try:
            document = _base_document(idx, "계획 실행 표본")
            document.add_paragraph("치환 대상 문단입니다.")
            table = document.add_table(2, 2, width=42000)
            table.cell(0, 0).text = "라벨"
            document.save_to_path(str(base_path))

            plan = {
                "schemaVersion": "hwpx.edit-plan/v1",
                "source": str(base_path),
                "output": str(out_path),
                "steps": [
                    {
                        "id": "s1",
                        "op": "paragraph_patch",
                        "args": {"patches": [{
                            "paragraphIndex": 3,
                            "text": f"계획으로 치환된 문단 {idx}",
                        }]},
                    },
                    {
                        "id": "s2",
                        "op": "fill_cells",
                        "args": {"cells": [{
                            "tableIndex": 0, "row": 0, "col": 1,
                            "text": cycle(DEPT_BANK, idx),
                        }]},
                    },
                ],
            }
            report = apply_edit_plan(plan)
            if not report.ok:
                raise RuntimeError(f"edit plan failed: {report.to_dict().get('failedStepId')}")
            records.append(record(
                rec_id=rec_id, bucket="edit-plan", seed=str(idx),
                output_path=out_path, produced=True, input_path=base_path,
            ))
        except Exception as exc:  # noqa: BLE001
            records.append(record(
                rec_id=rec_id, bucket="edit-plan", seed=str(idx),
                output_path=None, produced=False, input_path=base_path,
                withheld_reason=f"{type(exc).__name__}: {exc}",
            ))
    return records


GENERATORS: tuple[tuple[str, Callable[[Path], list[dict[str, Any]]]], ...] = (
    ("baseline-regen", gen_baseline_regen),
    ("authored-footnote", gen_footnote),
    ("authored-formfield", gen_formfield),
    ("authored-equation", gen_equation),
    ("authored-chart", gen_chart),
    ("authored-checkbox", gen_checkbox),
    ("edit-plan", gen_edit_plan),
)


def _tool_versions() -> dict[str, str | None]:
    from importlib.metadata import PackageNotFoundError, version

    versions: dict[str, str | None] = {}
    import hwpx

    versions["python-hwpx"] = str(hwpx.__version__)
    try:
        versions["python-hwpx-automation"] = version("python-hwpx-automation")
    except PackageNotFoundError:
        versions["python-hwpx-automation"] = None
    return versions


def _frozen_reference(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return {"path": str(path.relative_to(PYTHON_HWPX)), "sha256": sha256_file(path)}


def main() -> int:
    try:
        import hwpx_automation  # noqa: F401
    except ModuleNotFoundError:
        print(
            "ERROR: v3 requires the automation environment (the chart stratum "
            "composes ChartML through hwpx_automation.office.charting). Run "
            "with the automation venv, as v1 did.",
            file=sys.stderr,
        )
        return 2

    if OUT_DIR_V3.exists() and any(OUT_DIR_V3.iterdir()):
        print(
            f"ERROR: {OUT_DIR_V3} already exists — v3 is frozen once generated. "
            "Delete the tree explicitly to regenerate.",
            file=sys.stderr,
        )
        return 2

    all_records: list[dict[str, Any]] = []
    for bucket, generator in GENERATORS:
        bucket_dir = OUT_DIR_V3 / bucket
        bucket_dir.mkdir(parents=True, exist_ok=True)
        all_records += generator(bucket_dir)

    all_records.sort(key=lambda item: (item["bucket"], item["id"]))

    counts: dict[str, dict[str, Any]] = {}
    for entry in all_records:
        slot = counts.setdefault(
            entry["bucket"],
            {"requested": 0, "produced": 0, "withheld_ids": [], "static_unsafe_ids": []},
        )
        slot["requested"] += 1
        if entry["produced"]:
            slot["produced"] += 1
            if entry["static_open_safety_ok"] is False:
                slot["static_unsafe_ids"].append(entry["id"])
        else:
            slot["withheld_ids"].append(entry["id"])

    manifest = {
        "schemaVersion": MANIFEST_SCHEMA,
        "scopeNote": (
            "v3 is a REDUCED-SCOPE additive measurement: one baseline stratum "
            "plus one stratum per authoring surface added in 4.x/5.x. It does "
            "not replace the v1/v2 figures, which remain published with their "
            "own measurement stack and date."
        ),
        "generatedAt": None,  # root stamps it; determinism
        "toolVersions": _tool_versions(),
        "boxRoot": BOX_ROOT,
        "negativeControlsByReference": list(BOX_NEGATIVE_CONTROLS),
        "frozenPredecessors": {
            "v1": _frozen_reference(OUT_DIR / "manifest.json"),
            "v2": _frozen_reference(OUT_DIR_V2 / "manifest.json"),
        },
        "counts": counts,
        "requestedTotal": sum(slot["requested"] for slot in counts.values()),
        "producedTotal": sum(slot["produced"] for slot in counts.values()),
        "items": all_records,
    }
    manifest_path = OUT_DIR_V3 / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    filelist_path = OUT_DIR_V3 / "box_run_v3.filelist"
    lines = [
        f"{BOX_ROOT}\\{entry['bucket']}\\{entry['id']}.hwpx"
        for entry in all_records
        if entry["produced"]
    ]
    lines += list(BOX_NEGATIVE_CONTROLS)
    filelist_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"v3 corpus: {manifest['producedTotal']}/{manifest['requestedTotal']} produced")
    for bucket in sorted(counts):
        slot = counts[bucket]
        flags = ""
        if slot["withheld_ids"]:
            flags += f"  withheld={len(slot['withheld_ids'])}"
        if slot["static_unsafe_ids"]:
            flags += f"  STATIC-UNSAFE={slot['static_unsafe_ids']}"
        print(f"  {bucket:20s} {slot['produced']:3d}/{slot['requested']:3d}{flags}")
    print(f"manifest : {manifest_path}")
    print(f"filelist : {filelist_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
